'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ha';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    app_name: 'AgriFinance AI',
    hero_subtitle: 'Empowering smallholder farmers with access to fair micro-loans through AI-powered credit scoring based on real farming data, not just bank history.',
    farmer_onboarding: 'Farmer Onboarding',
    admin_portal: 'Lender Portal',
    onboarding: 'Onboarding',
    lenders: 'Lenders',

    sign_in: 'Sign In',
    sign_out: 'Sign Out',
    join_title: 'Join AgriFinance',
    join_desc: 'Enter your farm details below to see what loan products you qualify for.',
    analysis_title: 'Your Farm Analysis',
    analysis_desc: 'We have generated your AI-powered credit profile.',
    credit_grade: 'Credit Grade',
    score: 'Score',
    climate_risk: 'Climate Risk Level',
    our_analysis: 'Our Analysis',
    positive_factors: 'Positive Factors',
    risk_factors: 'Risk Factors',
    ussd_simulate: 'Simulate USSD / SMS Flow',
    ussd_desc: 'See how a farmer on a 2G connection without smartphone access receives their credit decision.',
    start_over: 'Start Over',
    share_sms: 'Share via SMS',
    download_report: 'Download Report',
    generate_score: 'Generate Credit Score',
    analyzing: 'Analyzing Farm Data...',
    full_name: 'Full Name',
    mobile_number: 'Mobile Number',
    region: 'Region / Location',
    primary_crop: 'Primary Crop',
    farm_size: 'Size (Acres)',
    est_yield: 'Est. Yield (Kg)',
    years_farming: 'Years Farming',
    farming_method: 'Farming Method',
    irrigation_check: 'I have access to reliable irrigation / water pump.',
    loan_check: 'I have previously taken and repaid a loan.',
    full_name_placeholder: 'e.g., Amina Bello',
    error_name: 'Please enter your full name.',
    error_phone: 'Please enter a valid phone number.',
    error_location: 'Please enter your location or region.',
    error_crop: 'Please enter your primary crop (e.g., Maize).',
    error_size: 'Please enter a valid farm size.',
    error_yield: 'Please enter a positive estimated yield.',
    error_experience: 'Please enter valid years of experience.',
    green_tips_title: 'Climate-Smart Farming Tips',
    green_tips_footer: 'Adopting these practices may increase your yield and improve your future credit score.',
    admin_title: 'Lender Portal (B2B)',
    admin_subtitle: 'Empowering financial inclusion through AI-driven risk assessment.',
    export_csv: 'Export to CSV',
    why_matters_title: 'Why this portal matters?',
    why_matters_desc: 'This dashboard is the bridge between millions of unbanked farmers and institutional capital. By translating farm data into a standardized credit score, we enable lenders like Babban Gona to provide credit without traditional collateral, directly tackling the inclusion gap.',
    filter_region: 'Filter by region (e.g. Gusau)',
    showing_profiles: 'Showing {count} profiles',
    table_farmer: 'Farmer',
    table_location: 'Location',
    table_crop: 'Crop',
    table_score: 'Credit Score',
    table_risk: 'Climate Risk',
    table_action: 'Action',
    view_details: 'View Details',
    modal_farm_details: 'Farm Details',
    modal_credit_health: 'Credit Health',
    approve_loan: 'Approve Loan',
    home_tagline: 'Empowering smallholder farmers with access to fair micro-loans through AI-powered credit scoring based on real farming data, not just bank history.',
    home_farmer_btn: 'Farmer Onboarding',
    home_admin_btn: 'Lender Portal',
    loan_matched_title: 'Matched Loan Products',
    loan_matched_subtitle: 'Based on your AI Credit Score',
    loan_apply: 'Apply',
    loan_interest: 'Interest',
    scorecard_label: 'Credit Score',
    scorecard_out_of: 'out of 100',
    savings_title: 'Community Savings Wallet',
    savings_active: 'Active',
    savings_total_label: 'Total Balance',
    savings_week1: 'Week 1',
    savings_week2: 'Week 2',
    savings_week3: 'Week 3',
    savings_add_btn: 'Add Small Savings (₦200 min)',
    savings_footer: 'Consistent saving builds your "Repayment Proof" profile and increases your credit limit.',
    improve_title: 'Score Improvement Path',
    improve_desc: 'Your current score is {score}. Here is how you can unlock better loan rates:',
    improve_irrigation_title: 'Add Irrigation Access',
    improve_irrigation_desc: 'Installing a water pump or rain-catchment system reduces crop failure risk.',
    improve_loan_title: 'Build Repayment History',
    improve_loan_desc: 'Successfully repaying even a small starter loan builds trust for larger credit.',
    improve_potential: 'Potential: +{n} points',
    improve_estimated: 'Estimated potential score:',
    sms_reply: 'Reply:',
    sms_hint: '(Type a number and press Enter)',
    sms_ussd_demo: 'USSD Demo',
    sms_sms_demo: 'SMS Demo',
    sms_score_title: 'AgriFinance Score',
    sms_score_text: 'Your current rating is:',
    sms_go_back: '0. Go Back',
    sms_loan_title: 'Loan Application',
    sms_loan_qualify: 'You pre-qualify for:',
    sms_accept: '1. Accept Offer',
    sms_success_title: 'Success!',
    sms_success_text: 'Your loan application for {amt} has been submitted to Babban Gona.',
    sms_main_menu: '0. Main Menu',
    sms_tips_title: 'Green Farming Tips',
    sms_tip_1: 'Tip 1: Retain crop residue after harvest to keep soil moisture high.',
    sms_lang_title: 'Language / Harshe',
    sms_lang_updated: 'Language setting updated successfully.',
    sms_welcome: 'Welcome to AgriFinance',
    sms_menu_1: '1. Apply for Loan',
    sms_menu_2: '2. Check My Score',
    sms_menu_3: '3. Green Farming Tips',
    sms_menu_4: '4. Language (Hausa/ENG)',
    sms_new_msg: '💬 NEW TEXT MESSAGE',
    sms_alert: 'AgriFinance Alert: Your farm analysis is ready!',
    sms_score_line: 'Score: {score}/100',
    sms_qualify_line: 'You qualify for a loan estimate of {amt}.',
    sms_reply_tips: "Reply 'TIPS' for local weather advice.",
    fin_empowerment: 'Financial Empowerment',
    fin_northern_alert: 'Northern Region Alert',
    fin_northern_text: 'The rainy season for Zamfara usually starts in June. Ensure your primary crop inputs (Sorghum/Maize) are secured by mid-May to avoid price hikes.',
    fin_tip1_title: 'Understanding Interest',
    fin_tip1_content: 'If you borrow ₦10,000 at 5%, you pay back ₦10,500. Always check the total repayment amount before signing.',
    fin_tip2_title: 'Crop Insurance',
    fin_tip2_content: 'Pula and NAIC offer index-based insurance. If your location (Zamfara) has no rain for 21 days, you get paid automatically.',
    fin_tip3_title: 'Building History',
    fin_tip3_content: 'Paying back 1 day early increases your score more than paying exactly on time. This earns lower rates later.',
    fin_borrowing: 'Borrowing',
    fin_resilience: 'Resilience',
    fin_credit: 'Credit',
    // LoanOffers modal
    loan_modal_title: 'Application Details',
    loan_modal_option1: 'Option 1: Dial USSD',
    loan_modal_option2: 'Option 2: Call Helpline',
    loan_modal_done: 'Done',
    loan_modal_cancel: 'Cancel',
    loan_modal_confirm: 'Confirm & Apply',
    loan_modal_lender: 'Lender',
    loan_modal_type: 'Loan Type',
    loan_modal_rate: 'Interest Rate',
    loan_modal_amount: 'Recommended Amt.',
    loan_modal_initiated: 'Application Initiated',
    loan_modal_initiated_desc: 'To complete your application with',
    loan_modal_initiated_suffix: 'please follow these steps:',
    // SavingsTracker modal
    savings_modal_title: 'Add Savings',
    savings_modal_amount_label: 'Amount (₦)',
    savings_modal_confirm: 'Confirm Savings',
    savings_modal_success_title: 'Savings Added!',
    savings_modal_success_desc: 'Your wallet balance has been updated.',
    savings_modal_min_error: 'Minimum amount is ₦200',
    // ScoreBreakdownChart
    score_breakdown_title: 'Score Breakdown',
    score_breakdown_experience: 'Experience',
    score_breakdown_farm_data: 'Farm Data',
    score_breakdown_climate: 'Climate',
    // Login page
    login_title: 'Sign in to AgriFinance',
    login_subtitle: 'Access your farm credit dashboard',
    login_phone_label: 'Phone Number',
    login_phone_placeholder: '+234 800 000 0000',
    login_send_otp: 'Send OTP',
    login_sending: 'Sending...',
    login_otp_label: 'Enter OTP',
    login_verify: 'Verify OTP',
    login_verifying: 'Verifying...',
    login_change_phone: 'Change phone number',
  },
  ha: {
    app_name: 'AgriFinance AI',
    hero_subtitle: 'Bada karfi ga kananan manoma da damar samun rance mai adalci ta hanyar auna kimar bashi da AI, dangane da ainihin bayanan noma ba kawai tarihin banki ba.',
    farmer_onboarding: 'Shigan Manomi',
    admin_portal: 'Portal Na Masu Ba Da Rance',
    onboarding: 'Shigarwa',
    lenders: 'Masu Ba da Rance',

    sign_in: 'Shiga',
    sign_out: 'Fita',
    join_title: 'Kasance da AgriFinance',
    join_desc: 'Shigar da bayanan gonar ku a kasa don ganin irin rancen da kuka cancanci samu.',
    analysis_title: 'Binciken Gonar Ku',
    analysis_desc: 'Mun samar da bayanan ku na bashi ta amfani da hankali na jabu (AI).',
    credit_grade: 'Matakin Bashi',
    score: 'Maki',
    climate_risk: 'Hadarin Yanayi',
    our_analysis: 'Binciken Mu',
    positive_factors: 'Abubuwa Masu Kyau',
    risk_factors: 'Abubuwan Hadari',
    ussd_simulate: 'Gwada USSD / SMS',
    ussd_desc: 'Ga yadda manomi mai amfani da tsohuwar waya (2G) yake samun sakamakon bashin sa.',
    start_over: 'Sake Farawa',
    share_sms: 'Aika ta SMS',
    download_report: 'Sauke Rahoton',
    generate_score: 'Samar da Makin Bashi',
    analyzing: 'Ana binciken bayanan gona...',
    full_name: 'Cikakken Suna',
    mobile_number: 'Lambar Wayar Hannu',
    region: 'Yanki / Wuri',
    primary_crop: 'Babban Amfanin Gona',
    farm_size: 'Fadin Gona (Acres)',
    est_yield: 'Yawan Amfanin Gona (Kg)',
    years_farming: 'Shekarun Noma',
    farming_method: 'Hanyar Noma',
    irrigation_check: 'Ina da damar yin amfani da ban-ruwan rani.',
    loan_check: 'Na taba karbar bashi kuma na biya a baya.',
    full_name_placeholder: 'Misali, Amina Bello',
    error_name: 'Da fatan za a shigar da cikakken sunan ku.',
    error_phone: 'Da fatan za a shigar da lambar waya mai aiki.',
    error_location: 'Da fatan za a shigar da yankin ku ko wurin ku.',
    error_crop: 'Da fatan za a shigar da babban amfanin gonar ku (misali, Bakandamiya).',
    error_size: 'Da fatan za a shigar da fadin gona mai inganci.',
    error_yield: 'Da fatan za a shigar da yawan amfani mai kyau.',
    error_experience: 'Da fatan za a shigar da shekarun gwaninta masu kyau.',
    error_failed: 'An gaza binciken bayanan gona',
    error_unexpected: 'An sami kuskuren da ba a zata ba. Da fatan za a sake gwadawa.',
    green_tips_title: 'Shawarwari Don Noma Mai Kyau',
    green_tips_footer: 'Bin wadannan shawarwari na iya kara yawan amfanin gona da kuma inganta makin bashin ku a nan gaba.',
    admin_title: 'Portal Na Masu Ba Da Rance (B2B)',
    admin_subtitle: 'Inganta hada-hadar kudi ta hanyar amfani da AI don auna hadarin bashi.',
    export_csv: 'Fitar da Bayanan CSV 📊',
    why_matters_title: 'Me yasa wannan portal din ke da muhimmanci?',
    why_matters_desc: 'Wannan dashboard din shi ne gada tsakanin miliyoyin manoma da ba su da asusun banki da babban jarin hukumomi. Ta hanyar fassara bayanan gona zuwa makin bashi mai inganci, muna baiwa masu ba da rance kamar Babban Gona damar ba da bashi ba tare da jingina ba, don rage tazarar hada-hadar kudi.',
    filter_region: 'Tace ta yanki (misali, Gusau)',
    showing_profiles: 'Ana nuna bayanan manoma {count}',
    table_farmer: 'Manomi',
    table_location: 'Wuri',
    table_crop: 'Amfani',
    table_score: 'Makin Bashi',
    table_risk: 'Hadarin Yanayi',
    table_action: 'Aiki',
    view_details: 'Duba Bayani',
    modal_farm_details: 'Bayanan Gona',
    modal_credit_health: 'Ingancin Bashi',
    approve_loan: 'Amince Da Bashi ✅',
    home_tagline: "Baiwa manoman ƙananan filaye damar samun rancen da ya dace ta hanyar tantance bashi ta amfani da hankali na jabu (AI) dangane da bayanan gona na gaske, ba tarihin banki kawai ba.",
    home_farmer_btn: 'Shigarwar Manomi',
    home_admin_btn: 'Portal Na Masu Ba Da Rance',
    loan_matched_title: 'Kayayyakin Ranci da Suka Dace',
    loan_matched_subtitle: 'Dangane da Makin Bashin AI Ku',
    loan_apply: 'Yi Amavani',
    loan_interest: 'Ruwan Riba',
    scorecard_label: 'Makin Bashi',
    scorecard_out_of: 'daga 100',
    savings_title: "Akwatin Adana Kuɗin Al'umma",
    savings_active: 'Mai Aiki',
    savings_total_label: "Jimillar Ma'adi",
    savings_week1: 'Mako na 1',
    savings_week2: 'Mako na 2',
    savings_week3: 'Mako na 3',
    savings_add_btn: 'Kara Ƙananan Adanci (min ₦200)',
    savings_footer: 'Adana kuɗi akai-akai yana gina bayanan "Tabbacin Biyan Bashi" ku kuma yana ƙara iyakar bashin ku.',
    improve_title: 'Hanyar Inganta Maki',
    improve_desc: 'Makin ku na yanzu shine {score}. Ga yadda za ku iya buɗe damar samun ƙarin ranci:',
    improve_irrigation_title: 'Samu Damar Ban-Ruwa',
    improve_irrigation_desc: 'Sanya famfo na ruwa ko tsarin tattara ruwan sama yana rage hadarin lalacewar amfanin gona.',
    improve_loan_title: 'Gina Tarihin Biyan Bashi',
    improve_loan_desc: 'Biya ƙaramin bashi da nasara yana gina amana don samun bashi mafi girma.',
    improve_potential: 'Yuwuwar: +{n} maki',
    improve_estimated: 'Yuwuwar maki mai yiwuwa:',
    sms_reply: 'Amsa:',
    sms_hint: '(Rubuta lamba kuma danna Enter)',
    sms_ussd_demo: 'Gwajin USSD',
    sms_sms_demo: 'Gwajin SMS',
    sms_score_title: 'Maki na AgriFinance',
    sms_score_text: 'Ƙimar ku ta yanzu ita ce:',
    sms_go_back: '0. Koma Baya',
    sms_loan_title: 'Neman Ranci',
    sms_loan_qualify: 'Kun cancanci:',
    sms_accept: '1. Karɓi Tayin',
    sms_success_title: 'Nasara!',
    sms_success_text: 'An aika bukatarku na ranci na {amt} zuwa Babban Gona.',
    sms_main_menu: '0. Menu Babba',
    sms_tips_title: 'Shawarwarin Noma Mai Kyau',
    sms_tip_1: 'Shawarar 1: Ajiye sauran amfanin gona bayan girbi don kiyaye danshi a ƙasa.',
    sms_lang_title: 'Harshe / Language',
    sms_lang_updated: 'An sabunta saitunan harshe cikin nasara.',
    sms_welcome: 'Barka da zuwa AgriFinance',
    sms_menu_1: '1. Nemi Ranci',
    sms_menu_2: '2. Duba Makin Ka',
    sms_menu_3: '3. Shawarwarin Noma Mai Kyau',
    sms_menu_4: '4. Harshe (Hausa/ENG)',
    sms_new_msg: '💬 SABON SAƘON RUBUTU',
    sms_alert: 'Faɗakarwa ta AgriFinance: Binciken gonar ku ya shiryu!',
    sms_score_line: 'Maki: {score}/100',
    sms_qualify_line: 'Kun cancanci ranci mai ƙimar {amt}.',
    sms_reply_tips: "Aika 'TIPS' don neman shawarar yanayi na gida.",
    fin_empowerment: 'Ƙarfin Hada-Hadar Kudi',
    fin_northern_alert: 'Faɗakarwa ta Yankin Arewa',
    fin_northern_text: 'Lokacin damina a Zamfara yawanci yana farawa a watan Yuni. Tabbatar da samun abubuwan shigar amfanin gonar ku na farko (Dawa/Masara) kafin tsakiyar Mayu don guje wa hauhawar farashin.',
    fin_tip1_title: 'Fahimtar Ruwan Riba',
    fin_tip1_content: 'Idan kun karɓi ₦10,000 da riba kashi 5%, za ku biya ₦10,500. Koyaushe duba jimlar kuɗin dawowar kafin sanya hannu.',
    fin_tip2_title: 'Inshora ta Amfanin Gona',
    fin_tip2_content: 'Pula da NAIC suna ba da inshora ta kan awo. Idan babu ruwan sama a wurin ku (Zamfara) na kwana 21, za a biya ku kai tsaye.',
    fin_tip3_title: 'Gina Tarihi',
    fin_tip3_content: 'Biyan bashi kwana ɗaya kafin lokaci yana ƙara maki ku fiye da biyan daidai da lokaci. Wannan yana baiwa ƙarancin riba a nan gaba.',
    fin_borrowing: 'Aro',
    fin_resilience: 'Juriya',
    fin_credit: 'Bashi',
    // LoanOffers modal
    loan_modal_title: 'Bayanan Aikace-Aikace',
    loan_modal_option1: 'Zaɓi na 1: Kira USSD',
    loan_modal_option2: 'Zaɓi na 2: Kira Layin Taimako',
    loan_modal_done: 'An Gama',
    loan_modal_cancel: 'Soke',
    loan_modal_confirm: 'Tabbatar & Nema',
    loan_modal_lender: 'Mai Ba Da Rance',
    loan_modal_type: 'Nau\'in Ranci',
    loan_modal_rate: 'Ƙimar Riba',
    loan_modal_amount: 'Adadin da Aka Ba da Shawara',
    loan_modal_initiated: 'An Fara Aikace-Aikacen',
    loan_modal_initiated_desc: 'Don kammala aikace-aikacenku tare da',
    loan_modal_initiated_suffix: 'da fatan bi wadannan matakai:',
    // SavingsTracker modal
    savings_modal_title: 'Kara Adanci',
    savings_modal_amount_label: 'Adadi (₦)',
    savings_modal_confirm: 'Tabbatar Adanci',
    savings_modal_success_title: 'An Kara Adanci!',
    savings_modal_success_desc: 'An sabunta ma\'aunin walat\'inka.',
    savings_modal_min_error: 'Mafi ƙarancin adadi shine ₦200',
    // ScoreBreakdownChart
    score_breakdown_title: 'Rarrabuwa ta Maki',
    score_breakdown_experience: 'Gwaninta',
    score_breakdown_farm_data: 'Bayanan Gona',
    score_breakdown_climate: 'Yanayi',
    // Login page
    login_title: 'Shiga AgriFinance',
    login_subtitle: 'Duba dashboard ɗin gonar ku',
    login_phone_label: 'Lambar Waya',
    login_phone_placeholder: '+234 800 000 0000',
    login_send_otp: 'Aika OTP',
    login_sending: 'Ana aika...',
    login_otp_label: 'Shigar da OTP',
    login_verify: 'Tabbatar da OTP',
    login_verifying: 'Ana tabbatarwa...',
    login_change_phone: 'Canza lambar waya',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
